// import { Mochiy_Pop_P_One } from "next/font/google";
import "./globals.css";

// const inter = Mochiy_Pop_P_One({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="select-none">
      <body>{children}</body>
    </html>
  );
}
